version: '3.5'
services:
  terminalserver:
    build: ./
    image: ubuntu-22.04
    container_name: ubuntu-22.04
    hostname: ubuntu
    restart: always
    shm_size: 1g
    environment:
       IDLETIME: 11
    ports:
      - "3389:3389"
      - "2222:22"
    volumes:
      - ssh:/etc/ssh/
      - home/:/home/

volumes:
  ssh:
  home:
